#!/bin/bash
#
# This shell script if placed in /etc/apcupsd
# will be called by /etc/apcupsd/apccontrol when the    
# UPS goes back on to the mains after a power failure.
# We send an email message to root to notify him.
#

scriptdir=$(dirname "${BASH_SOURCE[0]}")
status=$(/sbin/apcaccess status)

linev=$(grep "^LINEV" <<< "$status" | cut -d ':' -f 2- | sed 's/^ *//g')
linefreq=$(grep "^LINEFREQ" <<< "$status" | cut -d ':' -f 2- | sed 's/^ *//g')
tonbatt=$(grep "^TONBATT" <<< "$status" | cut -d ':' -f 2- | sed 's/^ *//g')
bcharge=$(grep "^BCHARGE" <<< "$status" | cut -d ':' -f 2- | sed 's/^ *//g; s/ Percent/%/')
timeleft=$(grep "^TIMELEFT" <<< "$status" | cut -d ':' -f 2- | sed 's/^ *//g;')
loadpct=$(grep "^LOADPCT" <<< "$status" | cut -d ':' -f 2- | sed 's/^ *//g; s/ Percent/%/')

"$scriptdir/send_to_telegram.sh" "Power: Switching back to mains at $linev, $linefreq. Remaining battery charge $bcharge: ${timeleft,,} remaining at $loadpct load."
# TODO: unpin the message
exit 0
